// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/api/person.ts";
import * as $3 from "./routes/blog.tsx";
import * as $4 from "./routes/blog/posts/[slug].tsx";
import * as $5 from "./routes/greet/[name].tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/mobile.tsx";
import * as $8 from "./routes/mysql.tsx";
import * as $9 from "./routes/sqlite.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/LemonDrop.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/api/person.ts": $2,
    "./routes/blog.tsx": $3,
    "./routes/blog/posts/[slug].tsx": $4,
    "./routes/greet/[name].tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/mobile.tsx": $7,
    "./routes/mysql.tsx": $8,
    "./routes/sqlite.tsx": $9,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/LemonDrop.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
